### ISSUE TITLE
Doesn't work Steam overwrites / renames webkit.css

### ISSUE THREAD

**Issue by Lightningblade** [zero318/BegoneWhatsNew#2]
On steam startup webkit.css gets overwritten / renamed into webkit.css.old when modified.

Even when restricting the permissions / making it read only.

I was able to make steam unable to change it, but it still doesn't work.

**Comment by Ammako** [comment]
You're not supposed to edit the default files. You're supposed to create a "skins" folder at the root of your Steam install, make a folder (named BegoneWhatsNew, for example), and extract the resources folder from the release into that custom skin folder. Then you go to your Steam settings --> Interface --> Select the skin you wish Steam to use, select BegoneWhatsNew, and click Yes to restart.

**Comment by Lightningblade** [comment]
Thank you
